apiVersion: v1
kind: Application
metadata:
  name: argocd-dummy-app
  namespace: argocd-dummy
spec:
  destination:
    namespace: argocd-dummy
    server: https://kubernetes.default.svc
  source:
    path: .
    repoURL: https://github.com/moby-codes/argocd-test-app1.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
